export const EL = {
    Translator: "Μεταφραστής", 
    TranslatorName: "Μιχάλης Π",
    Language: "Γλώσσα",
    ThisLanguage: "Ελληνικά",
    OK: "OK",
    SteelMill: "Χαλυβουργείο",
    StainlessSteelPlant: "Εργοστάσιο Ανοξείδωτου Ατσαλιού",
    CircuitFoundry: "Circuit Foundry",
    IntegratedCircuit: "Integrated Circuit",
    OilWell: "Πετρελαιοπηγή",
    Wood: "Ξύλο",
    LoggingCamp: "Δάσος",
    LumberMill: "Κούτσουρα",
    Lumber: "Κούτσουρα",
    Paper: "Χαρτί",
    PaperMill: "Εργοστάσιο Χαρτιού",
    Book: "Βιβλία",
    BookPublisher: "Εκδοτικός Οίκος Βιβλίων",
    OilRefinery: "Διυλιστήριο Πετρελαίου",
    Sell: "Πώληση",
    Upgrade: "Αναβάθμιση",
    Build: "Χτύσιμο",
    Inspect: "Inspect",
    Buildings: "Κτήρια",
    Iron: "Μέταλλο",
    Actions: "Ενέργειες",
    FuelType: "Επέλεξε Καύσιμο",
    FuelCost: "Κόστος Καυσίμου",
    FuelConsumption: "%{fuel} Κατανάλωση",
    FuelEconomy: "Fuel Economy",
    FuelProduction: "%{fuel} Production",
    FuelInStorage: "%{fuel} In Storage",
    Plastic: "Πλαστικό",
    FuelSurplus: "%{fuel} Surplus",
    Petrol: "Πετρέλαιο",
    Buy: "Αγορά",
    NoLiquidity: "No Liquidity",
    NoLiquidityTurnOffAutoSell: "There's not enough liquidity in the market for %{res}, auto sell has been turned off",
    Multiplier: "Πολλαπλασιαστής",
    MultiplierDesc: "Κάθε 10 επίπεδα, κερδίζεις +1 πολλαπλασιαστή",
    SellBuilding: "Πώληση Κτηρίου",
    PowerGrid: "Κατανάλωση Ενέργειας",
    TradeAmount: "Trade Amount",
    SortBy: "Ταξινόμηση Κατά",
    SortByPrice: "Τιμή",
    SortByAmount: "Ποσότητα",
    NotEnoughResourcesForTrade: "Not enough resource(s) in the Trade Center for this trade",
    NotEnoughResources: "Not enough resource(s) for this operation",
    Transportation: "Transportation",
    Cash: "Χρήματα",
    Aluminum: "Αλουμίνιο",
    ResearchPoint: "Πόντοι Έρευνας",
    Unlock: "Ξεκλείδωμα",
    BuildingUnlocked: "%{building} has been unlocked",
    Science: "Επιστήμη",
    ScienceFromPowerDesc: "Power plants produce a small amount of Science when generating power",
    Culture: "Κουλτούρα",
    School: "Σχολείο",
    University: "Πανεπιστήμιο",
    Polytechnic: "Polytechnic",
    Colosseum: "Κολοσσαίο",
    WindTurbine: "Ανεμογεννήτρια",
    Engine: "Μηχανή",
    EngineFactory: "Εργοστάσιο Μηχανών",
    CameraFactory: "Εργοστάσιο Καμερών",
    Camera: "Κάμερα",
    Gun: "Όπλα",
    GunFactory: "Εργοστάσιο Όπλων",
    Aircraft: "Αεροσκάφος",
    AircraftFactory: "Εργοστάσιο Αεροσκαφών",
    Zeppelin: "Ζέπελιν",
    ZeppelinFactory: "Εργοστάσιο Ζέπελιν",
    Tank: "Τανκ",
    TankFactory: "Εργοστάσιο Τανκ",
    MinimumTradingAmount: "You cannot trade lower than minimum amount",
    CoalPowerPlant: "Coal Power Plant",
    PetrolPowerPlant: "Petrol Power Plant",
    Copper: "Χαλκός",
    Gas: "Φυσικό Αέριο",
    GasPump: "Αγωγός Φυσικού Αερίου",
    GasPowerPlant: "Gas Power Plant",
    Missile: "Πύραυλος",
    MissileFactory: "Εργοστάσιο Πυράυλων",
    Rocket: "Ρουκέτες",
    RocketFactory: "Εργοστάσιο Ρουκετών",
    BuildingPermit: "Οικοδομική Άδεια",
    BuildingPermitDesc:
        "You have permit for %{amount} buildings, you have already built %{amountBuilt} and have %{amountLeft} left",
    BuildingLocked: "Building is not available yet, you need to unlock it in Research Lab first",
    BuildQueue: "Build Queue",
    BuildQueueDesc: "Αριθμός κτηρίων που βρίσκονται στην αναμονή",
    MaxBuilders: "Μέγιστοι Εργάτες",
    MaxBuildersDesc: "Αριθμός κτηρίων που μπορείς να χτίσεις ταυτόχρονα",
    Silicon: "Σιλικόνη",
    AluminumMine: "Ορυχείο Αλουμινίου",
    CopperMine: "Ορυχείο Χαλκού",
    SiliconMine: "Ορυχείο Σιλικόνης",
    IronMine: "Ορυχείο Μετάλλου",
    CoalMine: "Ανθρακωρυχείο",
    Headquarter: "Κεντρικά Γραφεία",
    ResearchLab: "Εργοστάσιο Έρευνας",
    TradeCenter: "Trade Center",
    Resources: "Πόροι",
    NotEnoughPower: "💡 Not enough power, consider increasing power supply",
    NotEnoughFuel: "Not enough %{fuel} for this operation",
    NotEnoughCash: "Not enough cash for this operation",
    NotEnoughSwissMoney: "Not enough Swiss money for this operation",
    BuildingNotEnoughFuel: "💡 Not enough %{fuel}",
    AutoSell: "Αυτόματη Πώληση",
    SellAll: "Πώληση Όλων",
    Change: "Αλλαγή",
    StatisticsBureau: "Statistics Bureau",
    LogisticsDepartment: "Logistics Department",
    From: "Από",
    Top20FuelCost: "Top 20 Fuel Cost",
    To: "To",
    TransportTime: "Χρόνος Μεταφοράς",
    TopN: "Top %{n}",
    Warehouse: "Αποθήκη",
    TradeWarehouse: "Freight Warehouse",
    Coal: "Κάρβουνο",
    Video: "Βίντεο",
    ClothingFactory: "Εργοστάσιο Ρούχων",
    Clothes: "Ρούχα",
    Fashion: "Μόδα",
    FashionFactory: "Εργοστάσιο Μόδας",
    VideoFarm: "Video Farm",
    SantaFactory: "Εργοστάσιο Άγιου Βασίλη",
    Santa: "Άγιος Βασίλης",
    Car: "Αυτοκίνητο",
    CarFactory: "Εργοστάσιο Αυτοκινήτων",
    Ship: "Ship",
    SolarPanel: "Solar Panel",
    SolarPanelDesc: "💡 Solar Panels only work 5 seconds out of every 10 seconds - all cycles are aligned",
    WindTurbineDesc: "💡 Wind Turbines only work 8 seconds out of every 10 seconds - cycles are not aligned",
    Movie: "Ταινίες",
    MovieStudio: "Στούντιο Ταινιών",
    Sitcom: "Sitcom",
    TVStudio: "TV Studio",
    PC: "Υπολογιστές",
    GameStudio: "Στούντιο Βιντεοπαιχνιδιών",
    Game: "Βιντεοπαιχνίδια",
    ComputerFactory: "Εργοστάσιο Υπολογιστών",
    Shipyard: "Ναυπηγείο",
    PowerUsage: "Power Usage",
    PowerSupply: "Power Supply",
    PowerSurplus: "Power Surplus",
    Level: "Επίπεδο",
    Power: "Power",
    CentralBank: "Κεντρική Τράπεζα",
    ResourceInput: "Εισαγωγές",
    ResourceOutput: "Εξαγωγές",
    ResourceStorage: "Storage",
    ResourceChange: "Change",
    ResourceInOutDesc: "💡 Tap on Out-In numbers above to highlight the corresponding output and input buildings",
    ResourceChart: "Resource Chart",
    MarketUpdateIn: "Market Update In %{time}",
    Income: "Income",
    Semiconductor: "Ημιαγωγοί",
    SemiconductorFactory: "Εργοστάσιο Ημιαγωγών",
    SemiconductorFab: "Semiconductor Fab",
    Steel: "Ατσάλι",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Φαρμάρισμα Bitcoin",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Φαρμάρισμα Dogecoin",
    Guitar: "Κιθάρες",
    GuitarFactory: "Εργοστάσιο Κιθάρας",
    Drum: "Ντραμς",
    DrumFactory: "Εργοστάσιο Ντραμς",
    RecordingStudio: "Στούντιο Ηχογράφησης",
    OperaHouse: "Όπερα",
    CoalGasificationPlant: "Coal Gasification Plant",
    GasProcessingPlant: "Gas Processing Plant",
    Music: "Μουσική",
    Glass: "Γυαλί",
    PhoneFactory: "Εργοστάσιο Κινητών Τηλεφώνων",
    Phone: "Κινητά Τηλέφωνα",
    GlassFactory: "Εργοστάσιο Γυαλιού",
    Oil: "Oil",
    Chromium: "Χρώμιο",
    ChromiumMine: "Ορυχείο Χρώμιου",
    Uranium: "Ουράνιο",
    EnrichedUranium: "Εμπλουτισμένο Ουράνιο",
    NuclearPowerPlant: "Πυρηνικός Σταθμός",
    UraniumEnrichmentPlant: "Σταθμός Εμπλουτισμένου Ουρανίου",
    UraniumMine: "Ορυχείου Ουρανίου",
    Titanium: "Τιτάνιο",
    TitaniumMine: "Ορυχείο Τιτανίου",
    TitaniumAlloyPlant: "Titanium Alloy Plant",
    ChromiumAlloyPlant: "Chromium Alloy Plant",
    Input: "Input",
    PanelPosition: "Panel Position",
    PanelPositionDesc: "Show side panel on left, right or auto (depends on current selected tile)",
    InputCapacity: "Input Capacity",
    InputCapacityPerCycle: "Input Capacity / Cycle",
    Output: "Output",
    OutputCapacity: "Output Capacity",
    OutputCapacityPerCycle: "Output Capacity / Cycle",
    ResourceDeposit: "Resource Deposit",
    RecommendedBuilding: "💡 This tile has %{resource} deposit",
    AdjacentBonus: "Adjacent Bonus",
    AdjacentBonusDesc: "You get %{bonus}% extra capacity for every adjacent working building of the same type",
    ConsiderIncreaseProduction: "💡 Consider increase %{resource} production",
    AlwaysTransportInput: "Stockpile Mode",
    AlwaysTransportInputTradeCenter: "Always Export",
    AlwaysTransportInputTradeCenterDesc:
        "Always transport resources to Trade Center, even if auto sell is not enabled for that resource",
    AlwaysTransportInputDesc: "Always transport input resources, even if they are above minimal production requirement",
    ProductionCycleLength: "Production Cycle",
    ProductionCycleLengthDesc:
        "Duration of one production cycle, measured in seconds. Lengthening the cycle will increase the input/output per cycle accordingly thus lower its priority when fetching input resources",
    MaxInputDistance: "Max Input Distance",
    MaxInputDistanceDesc:
        "The maximum distance this building can fetch input resources from, measured in number of tiles",
    AutoSellCapacity: "Auto Sell Capacity",
    AutoSellCapacityDesc: "Max amount of resources auto sell can handle per second, per resource",
    CurrentAutoSellCapacityMultiplier: "Current multiplier: x%{n}",
    AutoSellConcurrency: "Auto Sell Concurrency",
    AutoSellConcurrencyDesc: "Max number of resources auto sell can handle at the same time",
    MaxAutoSellConcurrencyReached:
        "You have reached maximum auto sell concurrency, turn off another auto sell to enable this one",
    CannotSellBuilding: "Cannot sell building at this time",
    WallStreet: "Wall Street",
    MarketCap: "Market Cap",
    MarketCapDesc: "Total market capitalization (i.e. market value) of your corporation",
    BuildingValuation: "Building Valuation",
    BuildingValuationDesc: "Total value of your buildings, including building permits and upgrades",
    ResourcesValuation: "Resources Valuation",
    ResourcesValuationDesc: "Total value of resources in your inventory",
    Battery: "Battery",
    BatteryFactory: "Battery Factory",
    RatingBuy: "Buy",
    RatingSell: "Sell",
    SwissShop: "Swiss Shop",
    RatingHold: "Hold",
    RatingOutperform: "Outperform",
    RatingUnderperform: "Underperform",
    StockRating: "Stock Rating",
    JetEngine: "Jet Engine",
    Helicopter: "Helicopter",
    Lithium: "Lithium",
    LithiumMine: "Lithium Mine",
    LiionBatteryFactory: "Li-ion Battery Factory",
    HelicopterFactory: "Helicopter Factory",
    Satellite: "Satellite",
    ToyFactory: "Toy Factory",
    Toy: "Toy",
    SpaceStation: "Space Station",
    SpaceStationFactory: "Space Station Factory",
    OperatingSystem: "Operating System",
    OperatingSystemCompany: "Operating System Inc",
    LinuxDistribution: "Linux Distribution",
    Internet: "Internet",
    WebBrowser: "Web Browser",
    Console: "Console",
    ConsoleFactory: "Console Factory",
    Train: "Train",
    TrainFactory: "Train Factory",
    ShoeFactory: "Shoe Factory",
    Shoes: "Shoes",
    ArtilleryFactory: "Artillery Factory",
    Artillery: "Artillery",
    SubmarineFactory: "Submarine Factory",
    Submarine: "Submarine",
    Spaceship: "Spaceship",
    RobotFactory: "Robot Factory",
    Robot: "Robot",
    SpaceshipFactory: "Spaceship Factory",
    SatelliteFactory: "Satellite Factory",
    JetEngineFactory: "Jet Engine Factory",
    StockRatingDesc:
        "Stock rating consensus from Wall Street analysts, which affects your market cap and is updated together with the market",
    InterestRate: "Overnight Interest Rate",
    InterestRateDesc: "Interest you earn on your market capitalization while you are offline",
    OfflineEarning: "Offline Earning",
    OfflineEarningDesc: "Offline Earning depends on your market cap and interest rate",
    PerMin: "%{amount}/min",
    OfflineEarningTime: "Offline Earning Time",
    OfflineEarningTimeDesc: "You will earn offline earning for up to this threshold",
    BuyPermit: "Buy Permit",
    NotEnoughBuildingPermit: "Not enough building permits. Please buy more to build new buildings",
    MovingAverage: "Moving Average",
    MovingAverageDesc: "Show moving average of change of resources instead of real-time change",
    AllowZoom: "Zoom",
    AllowZoomDesc: "Turn on zoom support. Use your mouse wheel to zoom. Current zoom is %{zoom}",
    AllowZoomMobileDesc: "Turn on zoom support. You can pinch to zoom. Current zoom is %{zoom}",
    Settings: "Settings",
    SellBuildingDesc:
        "Selling a building will refund you 50% of your investment and 50% of the resources will be transported to Trade Center",
    SellBuildingFullRefundDesc:
        "Building Recycle policy is active, selling a building will give you full refund until in %{time}",
    Sound: "Sound Effect",
    SoundDesc: "Turn on sound effect like click or error sound",
    AutoHighlight: "Auto Highlight",
    AutoHighlightDesc: "Automatically highlight buildings of the same type when you select a building",
    MusicDesc: "Turn on music: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Credits",
    Icons: "Icons",
    MisplacedBuilding: "⛔ This %{building} is not placed on top of the correct resource deposit",
    UnderConstruction: "%{building} is under construction",
    Left: "Left",
    Right: "Right",
    Auto: "Auto",
    HighlightBuildings: "Highlight Buildings",
    HighlightTurnedOff: "...that are shut down",
    HighlightStockpileModeOn: "...that have stockpile mode on",
    HighlightProductionCycleNotDefault: "...that have production cycle > 1",
    HighlightMaxInputDistanceNotDefault: "...that have max input distance < ∞",
    HighlightNotMakingProfit: "...do not make a profit",
    NBuildingsAreHighlighted: "%{n} building(s) are highlighted",
    OnlyToWarehouse: "Only for Warehouses",
    OnlyToWarehouseDesc: "Only warehouses can transport resources from this building",
    TurnOffProduction: "Shutdown",
    TurnOffProductionDesc:
        "Turn off the building's production. The building will no longer transport resources and use power",
    ApplyToAll: "Apply To All %{building}",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Unlimited",
    Transport: "Transport",
    TileModifier: "Tile Modifier",
    ShowAllModifiers: "Show All Modifiers",
    HideAllModifiers: "Hide All Modifiers",
    NumberOfBuildings: "Number of buildings you have",
    ShowContent: "Show Content",
    HideContent: "Hide Content",
    BuyExpansionPack: "Buy For %{price}",
    Cities: "Cities",
    WarehouseInputCapacityDesc: "Amount of resources the warehouse can transport inward per second, per resource.",
    InputStrategy: "Input Strategy",
    InputStrategyClose: "Closer",
    InputStrategyCloseDesc: "Prefer the closest warehouse which has enough resources",
    InputStrategyFar: "Farther",
    InputStrategyFarDesc: "Prefer the farthest warehouse which has enough resources",
    InputStrategyAmount: "Amount",
    InputStrategyAmountDesc: "Prefer the warehouse with the largest amount of the resources, regardless of distance",
    FuelCostSave: "Fuel Cost Save",
    FuelCostSaveDesc:
        "Warehouses save a certain percentage of fuel for transporting resources inward compared to other buildings, the higher the level, the more the save",
    SoftwareCompany: "Software Company",
    Software: "Software",
    ScreenFactory: "Screen Factory",
    Screen: "Screen",
    JoinDiscord: "Join our Discord server for latest updates, tips and discussions",
    ClaimOfflineEarning: "Claim Offline Earning",
    OfflineTime: "Offline Time",
    Minutes: "%{time}min",
    MaxUpgrade: "Max Upgrade",
    MaxUpgradeDesc: "You have reached maximum upgrade",
    ClaimAmount: "Cash +%{amount}",
    EarningPerMinute: "Earning Rate",
    EffectiveTime: "Effective Time",
    EffectiveTimeDesc: "Your effective offline earning time is capped at %{time}min.",
    BuildSearchPlaceholder: "Type building or resource to search",
    MineOverlayWarning: "%{building} is not affected by tile modifier",
    WholesaleCenter: "Wholesale Center",
    OrderFrom: "Order from %{name}",
    ExpireIn: "Expire In",
    ProfitMargin: "Profit Margin",
    NotMakingProfitWarning: "💡 Production not profitable, consider shut it down",
    TurnOnAllProductions: "Production On",
    TurnOnAllProductionsDesc: "Turn on productions of all buildings, cannot be used when Cost Saver policy is active",
    OperationSuccessful: "This operation has been successfully completed",
    TurnOn: "Turn On",
    Reward: "Reward",
    PerSecond: "%{time}/s",
    PerCycle: "%{amount}/cycle",
    PolicyPoint: "Policy Point",
    PolicyPointPerMinute: "Generate Rate",
    PolicyPointPerMinuteDesc: "You acquire policy points every minute in the game",
    YourWilLGaimPolicyPoints: "You will gain %{amount} policy points in %{time}s",
    PolicyPointDesc: "💡 The more active policies, the more cost for each policy",
    NextOrderIn: "Next Order In",
    FillOrder: "Fill Order",
    RejectOrder: "Pass",
    YouHave: "You have %{amount}",
    WholesaleCenterLocked:
        "You need at least %{required} different resources to unlock Wholesale Center. You only have %{current} resources",
    OrderFilled: "The order from %{from} has been successfully filled!",
    PolicyCenter: "Policy Center",
    NewOrder: "A new order from %{from} has arrived, please check in Wholesale Center",
    Policies: "Policies",
    PolicyNotEnoughTime: "You don't have enough policy points for this policy",
    TimeLeft: "%{time} Left",
    WholesaleCenterOrderFaster: "World's Fair",
    WholesaleCenterOrderFasterDesc: "Wholesale Center receives orders 2x faster and the order size is 2x bigger",
    PolicyOilWellPowerx2: "Supercharge Oil Well",
    PolicyOilWellPowerx2Desc: "Oil wells produce 2x oil and use 2x power",
    HalfTransportSpeed: "Slow Down To Save Up",
    HalfTransportSpeedDesc: "Transportation speed is slowed down by 25% and fuel cost is reduced by 25%",
    RefineryMoreOil: "Mo Petrol Mo Problems",
    RefineryMoreOilDesc: "Oil Refineries produce 50% more petrol and 50% less plastic",
    StickyInput: "Sticky Input",
    StickyInputDesc:
        "Buildings will prefer to transport from previous source, instead of searching for the best source every cycle (FREE POLICY)",
    RefineryMorePlastic: "Mo Plastics Mo Problems",
    RefineryMorePlasticDesc: "Oil Refineries produce 50% less petrol and 50% more plastic",
    FreeOilTransport: "Free Oil Transport",
    FreeOilTransportDesc: "Oil transport doesn't cost fuel but oil wells use 2x power",
    SuperSteelMill: "Hearts of Iron",
    SuperSteelMillDesc: "Steel mills use 50% less coal and 25% more iron and 25% more power",
    AlSemiconductor: "Al Circuit",
    AlSemiconductorDesc: "Circuit foundries use aluminum instead of copper",
    CostSaver: "Cost Saver",
    CostSaverDesc: "If a building's input cost more than its output, shut down the production",
    CostSaverBuildingDesc:
        "Cost Saver policy is active, production will turn on/off automatically based on its profitability",
    CostSaverBuildingWarning: "Cost Saver policy is active, you cannot manually change production",
    GlassUseCoal: "Black Glass",
    GlassUseCoalDesc: "Glass factories use 50% more coal and 50% less silicon",
    AdjacentBonusOnlyOutput: "Adjacent Bonus Plus",
    AdjacentBonusOnlyOutputDesc:
        "Adjacent bonus does not require more input but uses more power and is only 50% effective",
    IronMine2xOutput: "Heavy Iron",
    IronMine2xOutputDesc: "Iron mines produce 2x iron but iron transport costs 2x fuel",
    SolarPanelAlwaysWork: "The Sun Never Sets",
    SolarPanelAlwaysWorkDesc: "Solar panel works 100% of the time but produces 60% less power",
    SteelScience: "Knowledge Through Steel",
    SteelScienceDesc: "Steel mills use 2x input and produce extra science",
    ShowWarehouse: "Unlock Warehouse",
    ShowWarehouseDesc:
        "A warehouse is a special building that only transports and store resources and can provide fuel save (FREE POLICY)",
    WholesaleCenterProducingOnly: "Wholesale Partners",
    WholesaleCenterProducingOnlyDesc:
        "Wholesale center orders only contain resources that are currently being produced (you also need to be producing the number of required resources to unlock wholesale center)",
    ShoppingSpree: "Shopping Spree",
    ShoppingSpreeDesc:
        "If a resource's output capacity falls short, buy the shortage amount from Trade Center automatically (If the resource has auto sell on, it will be ignored)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Shopping Spree policy is on, Trade Center will automatically buy resources in shortage",
    ExtraPolicyPoints: "Political Lobbyist",
    ExtraPolicyPointsDesc: "Increase policy point production capacity by 50%",
    CrAlloyUseFe: "Chroiron",
    CrAlloyUseFeDesc: "Chromium alloy plants do not use Lithium but use 2x Iron instead",
    DoubleTileModifier: "Nature's Power",
    DoubleTileModifierDesc: "All tiles' modifier's effect x2 - both positive and negative",
    TileModifierOutputOnly: "Tile Modifier Plus",
    TileModifierOutputOnlyDesc:
        "Tile modifiers only affect output instead of both input and output but are only 50% effective",
    GasPlantPetrol: "Gas Liquidizer",
    GasPlantPetrolDesc: "Gas power plants use extra gas to produce petrol",
    BuildingRecycle: "Building Recycle",
    BuildingRecycleDesc: "Get full refund when you sell a building within 1 min after construction",
    CoalPlantFuel: "Coal Liquidizer",
    CoalPlantFuelDesc: "Coal power plants use extra coal to produce petrol",
    Welcome: "Welcome",
    SeeTutorialAgain: "Redo Tutorial",
    ReadSteamGuide: "Official Guide on Steam",
    HelpTranslateTheGame: "Help Translate the Game🌐",
    SkipTutorial: "Skip Tutorial",
    NextTutorial: "Next",
    Tutorial1:
        "Industry Idle is a <em>resource management</em> game where you build factories🏭, produce goods📦 and make money💸.<br><br>Let's go through some basic concepts to get you started - it won't take long, I pinky promise.",
    Tutorial2:
        "All buildings need power⚡, you have a <em>wind turbine</em> that generates power. You can see your current power supply on the left side of the top bar.<br><br>You might have noticed that wind turbines only work <em>80%</em> of the time. You can consider building other types of power plants that generate stable power.",
    Tutorial3:
        "You have a lot of <em>resource deposits</em> on the map. To extract resources, you have to build mines⛏️ <em>on top of</em> the corresponding deposit.<br><br>For example, you have an <em>oil well🛢️</em> that extracts <em>oil</em> from an oil deposit.<br></br>Resource deposits are unlimited - no need to worry about them running out. Apart from mines, other buildings can be built on any empty tile.",
    Tutorial4:
        "Resource transportation costs fuel. On this map, you can use <em>petrol⛽</em> as fuel. You have an <em>oil refinery</em> that transports oil from the oil well and produces petrol.<br><br>The tiny moving <em>dots</em> represent the real-time movement of resources. You should optimize your building locations to minimize the distance of travel.<br><br><em>Upgrading</em> your buildings will increase their output, but will also increase their power usage and input required.<br><br>You can change your fuel type in the transportation center🚦. Remember to make sure your fuel production is above consumption otherwise your production will halt when you run out of fuel.",
    Tutorial5:
        "To make money, you need to export your resources via the trade center. To do this, simply turn on <em>auto sell</em> for that resource.<br></br>You can also buy resources from the trade center as well. Remember <em>if you buy a resource, you will drive up the price</em> and if you sell a resource, you will drive down the price.<br><br>The market is <em>volatile</em> and the price📈 changes regularly.",
    Tutorial6:
        "To build new buildings, you need to unlock it first in the <em>research lab🧪</em>. The research lab also converts science to research points.<br><br>Your wind turbine (and other power plants) produces a small amount of science when running. And you can build school🏫 and other dedicated buildings to boost science later.<br><br>Now you have learned all the basics, start to build up your economy! Here are some <em>cash💸</em> and <em>petrol⛽</em> to give you a jump start.",
    WelcomePlay: "Play",
    WelcomePlayMuted: "Play (🔇Music)",
    Changelog: "Changelog",
    ChangelogGotIt: "Got It",
    Chat: "Chat",
    Send: "Send",
    Import: "Import",
    Export: "Export",
    SteamCloudBackup: "Steam Cloud Backup",
    LastBackupAt: "Last Backup",
    RestoreFromBackup: "Restore from Backup",
    RestoreFromBackupFail: "Failed to restore backup from Steam Cloud: are you sure there's a backup?",
    RestoreFromBackupTitle: "Are you sure?",
    RestoreFromBackupDesc:
        "You normally don't need to restore from cloud backup, unless your local save is lost. Cloud backup are a bit older than your local save",
    ChatMessages: "Chat Messages",
    ChatPlaceholder: "Type your message: max 100 chars",
    ChangeName: "Change",
    SaveName: "Save",
    NameValidationRule: "Your name should only contain letters and numbers and be between 5-15 chars",
    NameValidationRuleProfanity: "Your name should not contain profanity",
    ChatMessageRateLimit: "You can only send a new chat message every 10 seconds",
    NameSaved: "Your name has been changed successfully",
    NoMessages: "No new messages",
    Leaderboard: "Leaderboard",
    LeaderboardDesc: "The leaderboard score is all the Swiss money you've ever earned",
    Name: "Name",
    Rank: "Rank",
    Tips1: "Stock ratings have 5 levels: Buy, Overperform, Hold, Underperform and Sell",
    Tips2:
        "Buildings will stop transporting resources if there's already enough for production, unless you turn on stockpile mode",
    Tips3: "Fuel cost for resource transportation is determined by distance and amount of resources",
    Tips4: "Buildings will only transport a resource if the amount found on map exceeds the input capacity",
    Tips5: "Buildings will only transport a resource from Trade Center if auto sell is turned off for that resource",
    Tips6: "You can see the fuel cost for a resource under the corresponding input capacity section",
    Tips7: "If you buy a resource, you will drive up the price. If you sell a resource, you will drive down the price",
    Tips8: "You can see the chart for each resource's amount and its change over time in Statistics Bureau",
    Tips9: "Research points needed for a building is determined by the market price of it's input resources",
    Tips10: "Different resources are priced differently in market - always be prepared for market volatility",
    Tips11: "It's a good idea to always check your power and fuel supply before expanding your production",
    FPS30: "Energy Saving",
    OfflineModeDesc:
        "Cannot connect to the server: offline earnings will not be generated. Please check your internet connection",
    OptOut: "Opt Out",
    OptIn: "Reset and Enable",
    LeaderboardOptOut: "Leaderboard Opt-Out",
    LeaderboardOptOutDesc:
        "This will no longer send leaderboard score. PLEASE NOTE: if you want to enable leaderboard later, your data needs to be reset",
    LeaderboardOptIn: "Reset and Enable Leaderboard",
    LeaderboardOptInDesc: "Your data needs to be RESET before you can re-enable leaderboard, are you sure?",
    RewardAdsFailed: "Reward video did not complete",
    RewardAdsNotAvailable: "Reward video is not available (currently only iOS/Android is supported)",
    OfflineEarningDoubleSuccess: "You have doubled your offline earning",
    FPS30Desc:
        "Turn on energy saving mode will run the game at 30FPS instead of 60FPS. This will make your battery last longer",
    HighlightAll: 'Highlight "%{type}"',
    HighlightInput: "🔍 Highlight %{type} Input",
    HighlightOutput: "🔍 Highlight %{type} Output",
    TotalInput: "Total Input Capacity",
    TotalOutput: "Total Output Capacity",
    RunOutIn: "Out in %{time}",
    FuelRunOutWarning: "💡 Your fuel consumption exceeds production. When fuel runs out, your transportation will halt",
    InAmount: "In: %{number}",
    OutAmount: "Out: %{number}",
    SwissBank: "Swiss Bank",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "If you start in a new city, you will get %{money} 💵",
    RestorePurchases: "Restore Purchases",
    RestorePurchasesSuccess: "Your purchases have been restored",
    RestorePurchasesFailed: "Your purchases did not restore",
    ExpansionPacks: "Expansion Packs",
    ExpansionPack1: "Expansion Pack 1",
    ExpansionPack1Owned: "Expansion Pack 1",
    RequireExpansionPack1: "Expansion Pack 1",
    RequireExpansionPack1Desc: "This is only available for Expansion Pack 1",
    RequireAnyExpansionPack: "Expansion Packs Exclusive",
    RequireAnyExpansionPackDesc: "This feature requires you to own at least one of the expansion packs",
    HideRewardAd: "Hide Rewarded Ads",
    HideRewardAdDesc:
        "All in-game ads are optional rewarded ads. This will hide all the rewarded ad options from game.",
    HideDiscordBanner: "Hide Discord Banner",
    HideDiscordBannerDesc: "Hide Discord and storefront banner in the headquarter",
    HideChat: "Hide Chat Message",
    HideChatDesc: "Hide chat message from the bottom toolbar",
    SortedByDeficit: "Sorted By Deficit",
    PurchaseFailed: "The purchase did not complete",
    PurchaseSteamContinue: "Please finish your purchase on Steam",
    PurchaseSuccess: "The purchase has completed, thanks for your support",
    PrestigeCurrency: "Swiss Money 💵",
    RestartDesc: "💡 Just want to restart? You can tap on Start In A New City above and choose your current city",
    PrestigeGoBack: "Go Back",
    PermanentUpgradeDesc: "This upgrade will carry over if you start in a new city",
    ProductionMultiplier: "Production Multiplier",
    ProductionMultiplierDesc:
        "A boost to all your buildings' production capacity (including mines, factories, power plants, science and culture buildings)",
    FuelCostDiscount: "Fuel Cost Discount",
    FuelCostDiscountDesc: "Gives a discount to fuel cost when transporting resources",
    AutoSellCapacityMultiplier: "Auto Sell Capacity Multiplier",
    AutoSellCapacityMultiplierDesc:
        "A multiplier that is applied to your auto sell capacity reagardless of the current capacity",
    BuildingPermitCostDivider: "Building Permit Cost Divider",
    BuildingPermitCostDividerDesc: "Divide building permit cost by this divider",
    ExtraAdjacentBonus: "Extra Adjacent Bonus",
    ExtraAdjacentBonusDesc: "Extra bonus capacity for every adjacent working building of the same type",
    OfflineEarningMultiplier: "Offline Earning Multiplier",
    OfflineEarningMultiplierDesc: "A multiplier that applies to offline earnings",
    PrestigeAlertTitle: "Are you sure?",
    PrestigeAlertContent:
        "Your company will be liquidated. You will cash in %{amount} Swiss money and start a new company in %{city}",
    PrestigeCurrencyDesc:
        "This is the money in your secret Swiss bank account, you can carry it with you when you start in a new city",
    Prestige: "Cash In",
    Cancel: "Cancel",
    SaveFileCorrupted: "Save File Corrupted",
    CheatDetected: "Your old save did not pass server validation and cannot be read. You will start with a new save",
    LoadGameError: "Failed to Load Game",
    LoadGameErrorMessage: "Error message: %{message}",
    LoadGameErrorDesc: "Please check your Internet connection. If the problem persists, please contact support",
    ExpansionPackIncompatible:
        "You are importing a save with expansion packs but your game doesn't have the required expansion packs",
    SaveFileMigrated: "A New Era: Beta Is Here",
    SaveFileMigratedDesc:
        "Thank you for play testing in alpha. Your old map is not compatible but we have migrated your data and give you some bonus",
    ClaimSwissMoney: "Claim %{amount} Swiss Money 💵",
    SaveFileMigratedFinePrint:
        "Your market cap is converted to Swiss Money and your unspent Swiss money is carried forward. You will get 50% bonus Swiss money for play testing in alpha. Max Swiss money that can be carried forward is capped at 200",
    CashIn: "Cash In",
    CurrentCity: "Current City",
    CashInDesc:
        "Your will get this amount to your Swiss bank account if you start in a new city. It is based on your company's market cap and it must reach %{amount} before you can earn Swiss money",
    MoveToNewMap: "Start In A New City",
    CityName: "City",
    CitySize: "Map Size",
    GridType: "Grid Type",
    StartInThisCity: "Start In %{city}",
    CityBonus: "City Bonus",
    ResourceTilePercentage: "Resource Tiles",
    MapSquareGrid: "Square",
    MapHexGrid: "Hex",
    Stockholm: "Stockholm",
    StockholmBonus:
        "<li>Free level 4 wind turbine x1</li><li>Free level 4 oil well x1</li><li>Free level 2 oil refinery x1</li><li>Paper mills are unlocked</li><li>Logging camps have 2x output</li>",
    Rotterdam: "Rotterdam",
    RotterdamBonus:
        "<li>Steel Mills have 2x capacity</li><li>Stainless Steel Plants have 2x capacity</li><li>Free iron transportation</li><li>Steel transportation costs 50% less fuel</li><li>Start with 2x auto sell capacity</li><li>No tile modifiers</li>",
    Oslo: "Oslo",
    OsloBonus:
        "<li>Oil refineries have 2x capacity</li><li>Gas processing plants have 2x capacity</li><li>Petrol power plants have 2x capacity</li><li>Steel mills use natural gas instead of coal</li><li>Free oil transportation</li>",
    StPetersburg: "St. Petersburg",
    StPetersburgBonus:
        "<li>Uranium mines have 2x output</li><li>Uranium enrichment plants have 2x capacity</li><li>Uranium transportation costs 50% less fuel</li><li>Free gun transportation</li><li>Missile factories use enriched uranium instead of titanium and uranium</li>",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Zeppelin factories are unlocked</li><li>Semiconductor factories have 2x productivity</li><li>Shipyards have 2x capacity</li><li>Car factories have 2x capacity</li><li>Li-ion battery factories are unlocked</li>",
    Toulouse: "Toulouse",
    ToulouseBonus:
        "<li>Titanium mines have 2x output</li><li>Uranium enrichment plants have 2x productivity</li><li>Jet engine factories have 2x capacity</li><li>Aircraft factories have 2x productivity</li><li>Rocket factories use uranium instead of enriched uranium</li>",
    Rome: "Rome",
    RomeBonus:
        "<li>Colosseums are unlocked</li><li>Colosseums have 2x productivity</li><li>Start with level 5 policy center</li><li>Opera houses have 2x capacity</li><li>Recording studios also produce culture</li>",
    Detroit: "Detroit",
    DetroitBonus:
        "<li>Engine factories are unlocked</li><li>Engine factories have 2x productivity</li><li>Car factories have 2x capacity</li><li>Car factories do not need batteries</li><li>Train factories have 2x capacity</li>",
    Boston: "Boston",
    BostonBonus:
        "<li>Start with level 5 research lab</li><li>Polytechnics are unlocked</li><li>Polytechnics have 2x capacity</li><li>Schools have 2x capacity</li><li>University have 2x productivity</li>",
    HideNotProducing: "Hide resources that are not being produced",
    SortByStorage: "Storage",
    SortByProduction: "Production",
    SortByName: "Name",
    BuildingInProgressCannotPrestige:
        "You have building construction in progress, you cannot start in a new city until they are finished",
    PlayerTrade: "Player Trade",
    AddTradeFail: "Failed to add your trade",
    AddTradeExceedMaximumTrade:
        "You can only have maximum %{number} active trades, please claim or cancel one of them first",
    AddTradeSuccess: "Your trade has been added successfully",
    LoadTradeFail: "Failed to load player trades, please try again later",
    ClaimTradeFail: "Failed to claim this trade, please try again later",
    ClaimTradeSuccess: "Your trade has been claimed successfully: $%{cash} has been added to your account",
    CancelTradeSuccess: "Your trade has been cancelled successfully",
    CancelTradeFail: "Failed to cancel this trade, please try again later",
    AcceptTradeSuccess: "This trade has been accepted by you: %{resource} has been added to your trade center",
    AcceptTradeFail: "Failed to accept this trade, please try again later",
    PlayerTradeBanner: "Trade Resources with Other Players",
    PlayerTradeResource: "Resource",
    PlayerTradeAmount: "Amount",
    PlayerTradePrice: "Price $",
    PlayerTradeValue: "Value $",
    PlayerTradeWaiting: "Waiting...",
    UseTradeCenterPrice: "Use Trade Center Price",
    AddTrade: "Add Trade",
    ActiveTrades: "Active Trades",
    AcceptTrade: "Accept",
    CancelTrade: "Cancel",
    RefundTrade: "Refund",
    RefundTradeSuccess: "This trade has been refunded: %{resource} has been refunded to your trade center",
    RefundTradeFail: "Failed to refund this trade, please try again later",
    ClaimTrade: "Claim",
    RefreshTrade: "Refresh",
    PasteYourSave: "Please paste your save data",
    FailedToImportSave: "Failed to Import Save",
    FailedToImportSaveDesc: "Your save file is incompatible or corrupted: %{error}",
    SaveCopiedToClipboard: "Your save data has been copied to your clipboard",
    CancelActiveTradeFirst: "You have active player trades, please cancel/claim them first",
    FailedToCheckActiveTrade: "Failed to check active player trades, please try again later",
    PlayerTradePriceNotValid: "Trade price must be between %{min} and %{max} (2 x Last Market Update Price)",
    PlayerTradeQuotaExceed: "This trade has exceeded your quota",
    PlayerTradeAmountNotValid: "Trade amount must be greater than 0",
    PlayerTradeValidRange: "Range: %{min} ~ %{max}",
    PlayerTradeFilterPrice: "Below Market Price",
    PlayerTradeFilterCanAfford: "Can Afford",
    PlayerTradeQuota: "Quota Left: %{value}",
    PlayerTradeUnavailable:
        "You need to have at least one resource in production and in storage before you can trade with players",
    PlayerTradeToClaim: "Your have %{num} new trade(s) to claim in Player Trade",
    PowerBank: "Power Bank",
    PowerBankBuildDesc: "Store surplus power and provide power supply during shortage",
    WarehouseBuildDesc: "Transport and store any resources and with lower fuel cost",
    PowerBankChargeSpeed: "Charge Speed",
    PowerBankPowerLeft: "Power Left",
    PowerBankMoreCapacity: "Battery Saver",
    PowerBankMoreCapacityDesc: "Power banks charge at 50% speed but have 50% more capacity",
    PowerBankNotWorking: "⛔ Power banks only work next to a power plant",
    ExcludeBuildingsShutdown: "Exclude buildings that are shut down",
    ColorTheme: "Color Theme",
    ColorThemeDesc: "Color theme for game icons, highlight, grid and background. REQUIRES RELOAD",
    SiliconMine2xOutput: "Silicon Valley",
    SiliconMine2xOutputDesc:
        "Silicon mines produce 2x silicon but use 50% more power and silicon transport costs 50% more fuel",
    CoalMine2xOutput: "Industrial Revolution",
    CoalMine2xOutputDesc: "Coal mines produce 2x coal but use 50% more power and coal transport costs 50% more fuel",
    AlMine2xOutput: "Aluminum Smelting",
    AlMine2xOutputDesc: "Aluminum mines produce 2x aluminum and use 2x more power",
    LoggingCamp2xOutput: "Deforestation",
    LoggingCamp2xOutputDesc: "Logging camps produce 2x wood and wood transport costs 2x fuel",
    HideResourceMovement: "Hide Resource Movement",
    HideResourceMovementDesc:
        "This will hide resource movement (those tiny dots) by default and only show the movement when you select a building",
    PowerBankLeft: "Power Bank",
    ColorThemeEditor: "Color Theme Editor",
    ColorThemeEditorDesc: "You can override colors in the current color theme. You currently have %{num} overrides",
    ColorThemeEditorSave: "Save",
    ColorThemeEditorReset: "Reset",
    ColorThemeEditorResetAll: "Reset All",
    NewMessageMentions: "Κάποιος σε ανέφερε στο μήνυμα που έγραψε: %{message}",
    HideChatMentions: "Να μην εμφανίζονται ειδοποιήσεις όταν με αναφέρουν (κάνουν tag) στο chat",
    HideChatMentionsDesc: "Hide the audio and toast notification when a chat message mentions me,",
    PendingConstructionCannotReload: "You have building construction in progress, the game cannot reload",
    AcceptTradeFailRateLimit: "You can only accept one trade every %{time} seconds",
    DowngradeBuilding: "Downgrade",
    CancelTradeConfirmDialogTitle: "Ακύρωση Αυτής Της Ανταλλαγής;",
    CancelTradeConfirmDialogDesc:
        "Cancelling this trade will refund %{percent} of the resource to the Trade Center warehouse",
    CancelTradeConfirmDialogYes: "Ναι",
    CancelTradeConfirmDialogNo: "Όχι",
    WarehouseInputRoutes: "Input Routes",
    WarehouseAddInput: "Πρόσθεσε Δρομολόγιο",
    WarehouseTapToSelect: "Tap on Map to Select...",
    WarehouseFindOnMap: "🔍 Βρες στον χάρτη",
    WarehouseRemoveRoute: "Remove",
    WarehouseAddRouteFail: "Failed to add route: selected tile is not valid source",
    LevelN: "Level %{level}",
    Surplus: "Πλεόνασμα",
    Production: "Παραγωγή",
    Consumption: "Κατανάλωση",
};
